global:
  name: customer-abc-elasticsearch
  namespace: default
  esVersion: 7.17.3
  esURI: http://customer-abc-elasticsearch-headless:9200

deployment:
  replicas: 4
  serviceName: deploy-elasticsearch
  clusterNodes: elasticsearch-0,elasticsearch-1,elasticsearch-2
  containers:
    images: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi

  volumeClaimTemplates:
    storage: 10Gi
    storageClassName: default

persistence:
  enabled: true
  existingClaim: elasticsearch-pvc
  storageClass: "default"
  accessModes:
    - ReadWriteMany
  size: 10Gi

