---
- hosts: servers
  become: yes
  tasks:
    - name: Install NTP package
      apt:
        name: ntp
        state: present

    - name: Configure /etc/ntp.conf
      copy:
        dest: /etc/ntp.conf
        content: |
          tinker panic 0
          restrict default kod nomodify notrap nopeer noquery
          restrict -6 default kod nomodify notrap nopeer noquery
          restrict 127.0.0.1
          restrict -6 ::1
          server 192.168.0.252 minpoll 4 maxpoll 8
          server 192.168.0.251 minpoll 4 maxpoll 8
          server 192.168.0.0
          fudge 192.168.0.0 stratum 10
          driftfile /var/lib/ntp/drift
          keys /etc/ntp/keys

    - name: Restart NTP service
      service:
        name: ntp
        state: restarted
        enabled: yes
