---
- name: Configure Nagios Monitoring
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Nagios includes host and service configs
      lineinfile:
        path: /etc/nagios4/nagios.cfg
        line: "{{ item }}"
      loop:
        - "cfg_file=/etc/nagios4/hosts.cfg"
        - "cfg_file=/etc/nagios4/services.cfg"
      notify: restart nagios

    - name: Deploy Nagios host configuration
      template:
        src: "templates/hosts.cfg.j2"
        dest: "/etc/nagios4/hosts.cfg"
      notify: restart nagios

    - name: Deploy Nagios service configuration
      template:
        src: "templates/services.cfg.j2"
        dest: "/etc/nagios4/services.cfg"
      notify: restart nagios

  handlers:
    - name: restart nagios
      systemd:
        name: nagios
        state: restarted
